openapi: 3.2.0
info:
  title: Pulse Public Forms API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: Forms API
  description: API for managing forms and records in Pulse
paths:
  /forms/record/recordsByRef:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Ref ID
      description: 'Retrieve Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: recordsByRef
      parameters:
      - in: query
        name: refId
        description: Ref ID
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/recordsCountByRef:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records Count by Ref ID
      description: 'Retrieve Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: recordsCountByRef
      parameters:
      - in: query
        name: refId
        description: Ref ID
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/flattenRecordsByRef:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Flatten Records by Ref ID
      description: 'Retrieve Flatten Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: flattenRecordsByRef
      parameters:
      - in: query
        name: refId
        description: Ref ID
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/recordsByFormId:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Form ID
      description: 'Retrieve Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: recordsByFormId
      parameters:
      - in: query
        name: formId
        description: Form ID
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/recordsCountByFormId:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Form ID
      description: 'Retrieve Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: recordsCountByFormId
      parameters:
      - in: query
        name: formId
        description: Form ID
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/flattenRecordsByFormId:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Form ID
      description: 'Retrieve Flatten Records submitted by Form ID with or without Date Range.


        **Authorised Roles:** *ICMUser, OnboardingFormsUser, FormsUser, RCMUser*'
      operationId: flattenRecordsByFormId
      parameters:
      - in: query
        name: formId
        description: Form ID
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
  /forms/record/flattenRecordsByTag:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Flatten Records by Tag
      description: 'Retrieve Flatten Records submitted by Tag with or without Date Range


        **Authorised Roles:** *PRFAdmin*'
      operationId: flattenRecordsByTag
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
    post:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Tag and Fields
      description: 'Retrieve Records submitted by Tag with or without Date Range filter by Fields


        **Authorised Roles:** *PRFAdmin*'
      operationId: flattenRecordsByTagPost
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
      requestBody:
        content:
          appliation/json:
            schema:
              type: array
              items:
                type: string
              example:
              - data.TITLE
              - data.FIRSTNAME
              - data.DROMCV2Dhd
        description: Form Fields
        required: true
  /forms/record/recordsCountByTag:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records Count by Tag
      description: 'Retrieve Records Count submitted by Tag with or without Date Range


        **Authorised Roles:** *PRFAdmin*'
      operationId: recordsCountByTag
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
    post:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Tag and Fields
      description: 'Retrieve Records submitted by Tag with or without Date Range filter by Fields


        **Authorised Roles:** *PRFAdmin*'
      operationId: recordsCountByTagPost
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
      requestBody:
        content:
          appliation/json:
            schema:
              type: array
              items:
                type: string
              example:
              - data.TITLE
              - data.FIRSTNAME
              - data.DROMCV2Dhd
        description: Form Fields
        required: true
  /forms/record/recordsByTag:
    get:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Tag
      description: 'Retrieve Records submitted by Tag with or without Date Range


        **Authorised Roles:** *PRFAdmin*'
      operationId: recordsByTag
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
    post:
      security:
      - BearerJWT: []
      tags:
      - Forms API
      summary: Records by Tag and Fields
      description: 'Retrieve Records submitted by Tag with or without Date Range filter by Fields


        **Authorised Roles:** *PRFAdmin*'
      operationId: recordsByTagPost
      parameters:
      - in: query
        name: tag
        description: Tag
        required: true
        schema:
          type: string
      - in: query
        name: submittedStartDate
        description: Submitted Start Date Eg. 01/01/2023
        schema:
          type: string
      - in: query
        name: submittedEndDate
        description: Submitted End Date Eg. 31/01/2023
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
      requestBody:
        content:
          appliation/json:
            schema:
              type: array
              items:
                type: string
              example:
              - TITLE
              - FIRSTNAME
              - DROMCV2Dhd
        description: Form Fields
        required: true
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
