openapi: 3.2.0
info:
  title: Pulse Public Learning API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: Learning API
  description: API for managing learning info in Pulse
paths:
  /training/traininghistoryrecord/{hours}:
    get:
      security:
      - ApiKey: []
      tags:
      - Learning API
      summary: Retrieve training history records verified in the last specified number of hours
      description: Retrieve training history records verified in the last specified number of hours (defaults to 12 hours if no value is given)
      operationId: getTrainingHistory
      parameters:
      - in: path
        required: true
        name: hours
        description: The max number of hours to look back when retrieving training records based on their date of verification
        schema:
          type: number
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTrainingHistoryRecordsResponse'
        401:
          description: The provided API Key is invalid.
        403:
          description: An API Key must be provided to use this resource.
components:
  schemas:
    TrainingHistoryRecord:
      type: object
      properties:
        Payroll_Num:
          type: string
        Username:
          type: string
        Email:
          type: string
        Given_Name:
          type: string
        Surname:
          type: string
        Course_Name:
          type: string
        Course_Code:
          type: string
        Completion_Date:
          type: string
    GetTrainingHistoryRecordsResponse:
      type: array
      items:
        $ref: '#/components/schemas/TrainingHistoryRecord'
      example:
      - Payroll_Num: 1234
        Username: test.user
        Email: test_user@test.com
        Given_Name: Test
        Surname: User
        Course_Name: How to build an API
        Course_Code: api101
        Completion_Date: 17/05/2021 3:36:28 PM
      - Payroll_Num: 1235
        Username: test.user123
        Email: test_user123@test.com
        Given_Name: Tester
        Surname: User
        Course_Name: Agile Methodologies
        Course_Code: agile123
        Completion_Date: 9/05/2021 3:36:28 PM
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
