openapi: 3.2.0
info:
  title: Pulse Public Project API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: Project API
  description: API for managing project info in Pulse
paths:
  /project/projectexecutionfinancialsync:
    post:
      security:
      - BearerJWT: []
      tags:
      - Project API
      summary: Sends Project Component BIS data to Pulse
      description: 'Performs a bulk upsert of BIS financial information relating to specific project codes (Project Components) at the individual project execution level.

        This matches on existing Project Executions by Project Component, which have to be pre-filled in the Projects Module on the Pulse website.

        Some preliminary setup is required before this API endpoint can be consumed. Additionally, only Admin users in the Projects Module will be able to consume this API endpoint.

        Setup instructions:

        1. Contact Pulse support at support@pulsesoftware.com to enable the Pulse Public API. Make sure you follow the steps outlined in the Authentication section to enable JWT authentication.

        2. In the Projects module, navigate to the Admin page.

        3. Click ''Manage Forms''.

        4. In a form of your choice, add the new fields that you would like to populate using this API endpoint. Ensure you make a field named ''Project Component''. This field will contain the unique Project Component value required to link a Project Execution in Pulse to a BIS Financial information record.

        5. These fields will need to be linked to this API endpoint before it can be consumed. Contact Pulse support at support@pulsesoftware.com so that they can do this for you.

        6. Once the new fields have been linked to the API, navigate to the Project Executions page in the Projects module and view the details of a Project Execution you would like to update via the API.

        7. In the Project Component field you created in step 4, add the unique identifier that will link the Project Execution to a BIS financial information record.


        **Note**: if any of the linked fields are deleted and re-added, you will need to contact Pulse support (support@pulsesoftware.com) to re-link the fields to the API.


        **Authorised Roles:** *ProjectAdmin*'
      operationId: updateProjectComponent
      responses:
        200:
          description: OK. Request completed successfully. Please see the updatedProjectComponents list in the response for the Project Components updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProjectComponentResponse'
        400:
          description: Request completed with some validation errors. Please see response for validation errors and list of updated Project Components.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProjectComponentResponse'
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectComponent'
        description: BIS financial data to be added. Ensure you fill in the Project Component property of each record with the Project Component value of a Project Execution. Any fields representing the date of last update are not required in the body.
        required: true
components:
  schemas:
    UpdateProjectComponent:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UpdateProjectComponentData'
          example:
          - Project Component: W046-100
            Description: This is a test.
            Full Year Original Budget: 447085
            Full Year Revised Budget: 111771.36
            YTD Budget: 335314.1
            YTD Commitments: 447085.46
            YTD Actuals: 765454
            Available Budget: 125412
          - Project Component: W046-101
            Description: This is also a test.
            Full Year Original Budget: 44799.1
            Full Year Revised Budget: 111999.36
            YTD Budget: 999314.1
            YTD Commitments: 499085.46
            YTD Actuals: 87765
            Available Budget: 215545
    UpdateProjectComponentResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/UpdateProjectComponentResponseError'
          example:
          - error num: '0003'
            project-component: W046-100
            error message: Project-Component not found in Pulse.
            error detail: Please ensure that the Project-Component exists in Pulse.
          - error num: '0001'
            project-component: ''
            error message: Missing Project Component Id.
            error detail: Data must contain key 'Project Component'.
        updatedProjectComponents:
          type: array
          items:
            type: string
          example:
          - project component code 1
          - project component code 2
    UpdateProjectComponentResponseError:
      type: object
      properties:
        error num:
          type: string
          example: '0001'
        project-component:
          type: string
          example: W046-100
        error message:
          type: string
          example: Project-Component not found in Pulse.
        error detail:
          type: string
          example: Please ensure that the Project-Component exists in Pulse.
    UpdateProjectComponentData:
      type: object
      required:
      - Project Component
      properties:
        Project Component:
          type: string
          example: W046-100
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
