openapi: 3.2.0
info:
  title: Pulse Public User Details API v2 API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: User Details API v2
  description: API for managing user details in Pulse including additional attributes
paths:
  /security/UserDetails:
    get:
      security:
      - BearerJWT: []
      tags:
      - User Details API v2
      summary: Get user detail(s) in Pulse
      description: 'Get user detail(s) in Pulse including their user additional attributes.

        - If no query parameters are provided, returns all users.

        - If `email`, `username`, or `userId` is provided, returns the matching user.

        **Authorised Roles:** *PulseSecurityUser*'
      parameters:
      - in: header
        name: x-api-key
        description: API key
        required: true
        schema:
          type: string
      - in: query
        name: email
        description: Email address
        required: false
        schema:
          type: string
      - in: query
        name: username
        description: Username
        required: false
        schema:
          type: string
      - in: query
        name: userId
        description: User Id
        required: false
        schema:
          type: string
      responses:
        200:
          description: 'OK. Request completed successfully.

            - If no query parameters are provided, returns all users as an array.

            - If a query parameter is provided, returns an array with a single user or empty array if not found.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfos'
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
        404:
          description: User not found by specified identifier
      operationId: getSecurityUserDetails
      x-operation-id-source: derived
    post:
      security:
      - BearerJWT: []
      tags:
      - User Details API v2
      summary: Update user in Pulse
      description: 'Update user in Pulse based on userId provided in request body


        **Authorised Roles:** *PulseSecurityUser*'
      parameters:
      - in: header
        name: x-api-key
        description: API key
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserInfo'
        description: User detail
        required: true
      operationId: postSecurityUserDetails
      x-operation-id-source: derived
    put:
      security:
      - BearerJWT: []
      tags:
      - User Details API v2
      summary: Update user in Pulse
      description: 'Update user in Pulse based on userId provided in request body


        **Authorised Roles:** *PulseSecurityUser*'
      parameters:
      - in: header
        name: x-api-key
        description: API key
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
        404:
          description: User not found by specified user id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
        description: User detail
        required: true
      operationId: putSecurityUserDetails
      x-operation-id-source: derived
    patch:
      security:
      - BearerJWT: []
      tags:
      - User Details API v2
      summary: Update user in Pulse
      description: 'Update user in Pulse based on userId provided in request body


        **Authorised Roles:** *PulseSecurityUser*'
      parameters:
      - in: header
        name: x-api-key
        description: API key
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsV2Response'
        401:
          description: Missing JWT Bearer token in the Authorization header or the given JWT token is invalid.
        403:
          description: The user corresponding to the given JWT token does not have access to this module.
        404:
          description: User not found by specified user id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
        description: User detail
        required: true
      operationId: patchSecurityUserDetails
      x-operation-id-source: derived
components:
  schemas:
    UserOnboardingDetailsDTO:
      type: object
      properties:
        portalID:
          type: integer
          format: int32
        portalName:
          type: string
        activeDate:
          type: string
        dueDate:
          type: string
    UserDetailsV2ApiError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    AdditionalAttributesDTO:
      type: object
      properties:
        tabId:
          type: integer
          format: int32
        tabName:
          type: string
        attributeId:
          type: integer
          format: int32
        attributeName:
          type: string
        attributeValue:
          type: string
        attributeDataType:
          type: string
    UserInfo:
      type: object
      properties:
        active:
          type: boolean
        userId:
          type: string
          format: uuid
        title:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        preferredName:
          type: string
        dateOfBirth:
          type: string
        gender:
          type: string
        mobilePhone:
          type: string
        workPhone:
          type: string
        telephone:
          type: string
        primaryEmail:
          type: string
        additionalEmail:
          type: string
        home_AddressLine1:
          type: string
        home_AddressLine2:
          type: string
        home_City:
          type: string
        home_Country:
          type: string
        home_PostCode:
          type: string
        home_State:
          type: string
        postal_AddressLine1:
          type: string
        postal_AddressLine2:
          type: string
        postal_City:
          type: string
        postal_Country:
          type: string
        postal_PostCode:
          type: string
        postal_State:
          type: string
        postalIsHome:
          type: boolean
        username:
          type: string
        payrollNumber:
          type: string
        divisionCode:
          type: string
        divisionName:
          type: string
        unitCode:
          type: string
        unitName:
          type: string
        sectionCode:
          type: string
        sectionName:
          type: string
        supervisorEmail:
          type: string
        teamName:
          type: string
        pulseRepresentativeEmail:
          type: string
        employmentStartDate:
          type: string
        employmentEndDate:
          type: string
        reasonOfTermination:
          type: string
        emergencyContact1_Name:
          type: string
        emergencyContact1_Relationship:
          type: string
        emergencyContact1_AddressLine1:
          type: string
        emergencyContact1_AddressLine2:
          type: string
        emergencyContact1_City:
          type: string
        emergencyContact1_State:
          type: string
        emergencyContact1_Country:
          type: string
        emergencyContact1_Postcode:
          type: string
        emergencyContact1_Mobile:
          type: string
        emergencyContact1_WorkPhone:
          type: string
        emergencyContact1_Telephone:
          type: string
        emergencyContact1_Email:
          type: string
        emergencyContact2_Name:
          type: string
        emergencyContact2_Relationship:
          type: string
        emergencyContact2_AddressLine1:
          type: string
        emergencyContact2_AddressLine2:
          type: string
        emergencyContact2_City:
          type: string
        emergencyContact2_State:
          type: string
        emergencyContact2_Country:
          type: string
        emergencyContact2_Postcode:
          type: string
        emergencyContact2_Mobile:
          type: string
        emergencyContact2_WorkPhone:
          type: string
        emergencyContact2_Telephone:
          type: string
        emergencyContact2_Email:
          type: string
        primaryPositionNumber:
          type: string
        primaryPositionName:
          type: string
        primaryPositionStartDate:
          type: string
        primaryPositionEndDate:
          type: string
        primaryPositionNotes:
          type: string
        employmentType:
          type: string
        onboarding:
          type: array
          items:
            $ref: '#/components/schemas/UserOnboardingDetailsDTO'
        additionalPositions:
          type: array
          items:
            $ref: '#/components/schemas/UserAdditionalPositionDTO'
        roles:
          type: array
          items:
            type: string
        userAdditionalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalAttributesDTO'
    UserAdditionalPositionDTO:
      type: object
      properties:
        positionNo:
          type: string
        positionName:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        notes:
          type: string
        supervisorEmail:
          type: string
    UserInfos:
      type: array
      items:
        $ref: '#/components/schemas/UserInfo'
    AddUserInfo:
      allOf:
      - $ref: '#/components/schemas/UserInfo'
      - type: object
        properties:
          password:
            type: string
          confirmPassword:
            type: string
          sendWelcomeEmail:
            type: boolean
    UserDetailsV2Response:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/UserDetailsV2ApiError'
        data:
          $ref: '#/components/schemas/UserInfo'
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
