openapi: 3.2.0
info:
  title: Pulse Public Recruitment API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: Recruitment API
  description: API for managing recruitment info in Pulse
paths:
  /rcm/jobs/jobsV2:
    get:
      tags:
      - Recruitment API
      summary: Jobs records
      description: Retrieve Recruitment Job Records secured by Private API key
      parameters:
      - in: header
        name: x-api-key
        description: API key
        required: true
        schema:
          type: string
      - in: query
        name: internalOnly
        description: Returns only Recruitment Jobs that are marked as Internal
        schema:
          type: boolean
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: The provided API Key is invalid.
        403:
          description: API Key must be provided to use this resource.
      operationId: getRcmJobsJobsV2
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
