openapi: 3.2.0
info:
  title: Pulse Public User Details API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: User Details API
  description: API for managing user details in Pulse
paths:
  /security/users/{value}:
    get:
      security:
      - ApiKey: []
      tags:
      - User Details API
      summary: Retrieve user details
      description: Retrieves a list of users matching a provided user identifier. Includes an 'active' flag which indicates whether or not a user is active.
      operationId: getUser
      parameters:
      - name: value
        in: path
        description: UserID, Username or Email of the desired user.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetResponse'
        403:
          description: Missing x-api-key or the given x-api-key does not grant client with access to this API.
        404:
          description: User not found in Pulse.
  /security/users:
    get:
      security:
      - ApiKey: []
      tags:
      - User Details API
      summary: Retrieve a complete list of users in Pulse
      description: Returns a list of all users in Pulse (including inactive users). Includes an 'active' flag which indicates whether or not a user is active.
      operationId: getUsers
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetResponse'
        403:
          description: Missing x-api-key or the given x-api-key does not grant client with access to this API.
    post:
      security:
      - ApiKey: []
      tags:
      - User Details API
      summary: Add a new user to Pulse
      description: Notifications can be enabled for this endpoint. Contact Pulse support at support@pulsesoftware.com to enable notifications via the UserSyncEnableNotification config.
      operationId: addUser
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserResponse'
        403:
          description: Missing x-api-key or the given x-api-key does not grant client with access to this API.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User object to be created
        required: true
    put:
      security:
      - ApiKey: []
      tags:
      - User Details API
      summary: Replaces an existing user in Pulse or creates a user if the specified user does…
      description: Notifications can be enabled for this endpoint. Contact Pulse support at support@pulsesoftware.com to enable notifications via the UserSyncEnableNotification config.
      operationId: updateUser
      responses:
        200:
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserResponse'
        403:
          description: Missing x-api-key or the given x-api-key does not grant client with access to this API.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
        description: User object to be updated to
        required: true
    delete:
      security:
      - ApiKey: []
      tags:
      - User Details API
      summary: Delete a user from Pulse
      description: Deletes a user from Pulse using the given userId or email
      operationId: deleteUser
      responses:
        200:
          description: ''
        403:
          description: Missing x-api-key or the given x-api-key does not grant client with access to this API.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteUser'
        description: Requires a <strong>UserId</strong> or <strong>Email</strong> in order lookup the user to delete from Pulse.
        required: true
components:
  schemas:
    UpdateUser:
      type: object
      required:
      - userId
      - email
      properties:
        userId:
          type: string
          example: 00000000-0000-0000-0000-000000000000
        email:
          type: string
          example: testuser@mail.com
        firstName:
          type: string
          example: Johnny
        lastName:
          type: string
          example: Samson
        additionalPositions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalPosition'
        roles:
          type: array
          items:
            type: string
            example: cpruser
        phone:
          type: string
          example: (02) 9983 0039
        mobile:
          type: string
          example: +61 412 030 992
        streetAddress:
          type: string
          example: 1 Talavera Rd
        suburb:
          type: string
          example: Macquarie Park
        state:
          type: string
          example: NSW
        postcode:
          type: string
          example: '2113'
        country:
          type: string
          example: Australia
        payrollNumber:
          type: string
          example: A123B
        positionNumber:
          type: string
          example: '1005'
        positionName:
          type: string
          example: Financial Accountant
        supervisorEmail:
          type: string
          example: super@gmail.com
        divisionName:
          type: string
          example: Business Performance
        divisionCode:
          type: string
          example: BP
        unitName:
          type: string
          example: Finance
        unitCode:
          type: string
          example: FIN
        sectionName:
          type: string
          example: Financial Accounting
        sectionCode:
          type: string
          example: FA
    UpdateUserResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/PulseApiError'
        data:
          $ref: '#/components/schemas/GetResponse'
    DeleteUser:
      type: object
      required:
      - userId
      - email
      properties:
        userId:
          type: string
          example: 00000000-0000-0000-0000-000000000000
        email:
          type: string
          example: jbjovi@gmail.com
      xml:
        name: DeleteUser
    OnboardingEnrolment:
      type: object
      required:
      - enrol
      properties:
        enrol:
          type: boolean
          example: 'true'
        portalId:
          type: integer
          example: '1'
        dueDate:
          type: string
          example: '2021-12-30'
        activeDate:
          type: string
          example: '2020-12-30'
    User:
      type: object
      required:
      - firstName
      - lastName
      - email
      properties:
        active:
          type: boolean
          example: true
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Jovi
        networkLogin:
          type: string
          example: johnj
        phone:
          type: string
          example: (02) 9983 0039
        mobile:
          type: string
          example: +61 412 030 992
        streetAddress:
          type: string
          example: 1 Talavera Rd
        suburb:
          type: string
          example: Macquarie Park
        state:
          type: string
          example: NSW
        postcode:
          type: string
          example: '2113'
        country:
          type: string
          example: Australia
        payrollNumber:
          type: string
          example: A123B
        positionNumber:
          type: string
          example: '1005'
        positionName:
          type: string
          example: Financial Accountant
        applicationDate:
          type: string
          example: '2020-12-30'
        supervisorEmail:
          type: string
          example: super@gmail.com
        onboarding:
          $ref: '#/components/schemas/OnboardingEnrolment'
        additionalPositions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalPosition'
        roles:
          type: array
          items:
            type: string
            example: cpruser
        divisionName:
          type: string
          example: Business Performance
        divisionCode:
          type: string
          example: BP
        unitName:
          type: string
          example: Finance
        unitCode:
          type: string
          example: FIN
        sectionName:
          type: string
          example: Financial Accounting
        sectionCode:
          type: string
          example: FA
        userId:
          type: string
          example: 00000000-0000-0000-0000-000000000000
        email:
          type: string
          example: jbjovi@gmail.com
      xml:
        name: User
    AdditionalPosition:
      type: object
      required:
      - startDate
      - endDate
      properties:
        positionNumber:
          type: string
          example: '1006'
        positionName:
          type: string
          example: Financial Accountant
        startDate:
          type: string
          example: '2021-02-11'
        endDate:
          type: string
          example: '2021-08-11'
    PulseApiError:
      type: object
      properties:
        code:
          type: string
          example: PRF/ProgressUpdate/Reference_MissingReference
        detail:
          type: string
          example: Mandatory field Reference was not supplied.
        source:
          type: string
          example: /data/0/uniqueReference
    GetResponse:
      type: object
      properties:
        active:
          type: boolean
          example: true
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Jovi
        networkLogin:
          type: string
          example: johnj
        phone:
          type: string
          example: (02) 9983 0039
        mobile:
          type: string
          example: +61 412 030 992
        streetAddress:
          type: string
          example: 1 Talavera Rd
        suburb:
          type: string
          example: Macquarie Park
        state:
          type: string
          example: NSW
        postcode:
          type: string
          example: '2113'
        country:
          type: string
          example: Australia
        payrollNumber:
          type: string
          example: A123B
        positionNumber:
          type: string
          example: '1005'
        positionName:
          type: string
          example: Financial Accountant
        applicationDate:
          type: string
          example: '2020-12-30'
        supervisorEmail:
          type: string
          example: super@gmail.com
        onboarding:
          $ref: '#/components/schemas/OnboardingEnrolment'
        additionalPositions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalPosition'
        roles:
          type: array
          items:
            type: string
            example: cpruser
        divisionName:
          type: string
          example: Business Performance
        divisionCode:
          type: string
          example: BP
        unitName:
          type: string
          example: Finance
        unitCode:
          type: string
          example: FIN
        sectionName:
          type: string
          example: Financial Accounting
        sectionCode:
          type: string
          example: FA
        userId:
          type: string
          example: 00000000-0000-0000-0000-000000000000
        email:
          type: string
          example: jbjovi@gmail.com
      xml:
        name: User
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
