openapi: 3.2.0
info:
  title: Pulse Public Authentication API
  version: 1.0.1
  description: The Pulse API is targeted towards developers looking to automate tasks in Pulse.
  termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsesoftware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://*.pulsesoftware.com/webservices/api
- url: http://*.pulsesoftware.com/webservices/api
tags:
- name: Authentication
  description: Authentication for accessing Pulse Public API
paths:
  /pulse/jwt:
    get:
      security:
      - ApiKey: []
      tags:
      - Authentication
      summary: Issue JWT Bearer Token
      description: Issues a JSON Web Token for authentication with a 60 minute expiry. If requested using User API Key, token will be granted all role privileges of the User. If requested using Application API Key, no role privileges will be granted.
      operationId: getJwtToken
      responses:
        200:
          description: OK. Request completed successfully.
        401:
          description: Authorization failed.  x-api-key is missing or invalid.
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-Api-Key
      in: header
    BearerJWT:
      type: apiKey
      name: Authorisation
      in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
